### ISSUE TITLE
Generalized code

### ISSUE THREAD

**Issue by bee-rock** [mrakgr/Parallel-Permutation-Algorithm#2]
Hi mrakgr,

Currently the code only permutes vectors of the type [1,2,3, ..., n] 

I'm struggling to understand how to adapt the code to permute an arbitrary vector. Any help would be appreciated.

Cheers,
Brock

**Comment by mrakgr** [comment]
http://www.cplusplus.com/reference/map/map/at/

Consider the C++ map container from the standard library. Given a vector of of type [1,2,3] and a map of type [int, int], you can loop an array through the map so that it transforms it like m[1] -> x, m[2] -> y, m[3] -> z and so on for different kinds of vectors.

And since the function really only has integer values, you can pretty much replace the map m with a standard array.

I hope that helps,
Marko

Edit: Let me put it a bit better.

Suppose you have an array a, a map m and an empty output array o, then what you would have to do is (in pseudo-code):
for (int i=0;i < a.Length;i++){
   o[i] = m[a[i]];
}

**Comment by bee-rock** [comment]
Ah! Thank you. One question though, the mapping can't be done prior to the permutation matrix being generated? Perhaps I'm optimistic in thinking that all the elements of the matrix would not have to be touched over again or maybe I'm still missing a piece of the puzzle.

**Comment by mrakgr** [comment]
Sorry for replying so late. It seems the Windows notification manager only tells me sporadically when a person talks to me...ugh. I'll check this section more regularly for replies from here.

To answer your question, it has been a while since I made that algorithm, but I think it has to be 1..n because it uses various bitwise operations to orient itself. You are going to have to write the map kernel yourself in CUDA unfortunately. I would recommend copying the actual map into constant memory for maximum performance.

Edit: I've taken a look at it again. I've completely forgotten about the details of how it works, but it is clear to me that the way to speed up this algorithm would be to merge the two kernels into one and to store the intermediates into shared memory.

And then while the variables are still in the fast memory, then apply the map pass.

Also if I was making the algorithm today, I would make the individual threads work more, maybe dedicate a thread to each column. That way instead of storing the values in shared memory, you could store them in the even faster local register memory. I think that way you could get over a 1,000x speedup over the CPU. 

Today, most of the bottlenecks in speed are because of moving the data to and from the very slow main memory, so by making use of the much faster local memory significant speedups are possible.

If what I've written here sounds confusing, I would suggest the parallel programming class on edX, it is better made than the one on Coursera.

**Comment by bee-rock** [comment]
No worries, thanks for the reply. I was indeed able to a create a mapping kernel like you had mentioned. I'll certainly look into your suggestions while I'm experimenting. Thanks again!
